language: php
php:
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2

before_install:
- "travis_retry composer install"

script:
- "./vendor/bin/phpunit ./tests  --coverage-clover=coverage.clover"

after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  email: false